### ISSUE TITLE
Doesnt work on android 13

### ISSUE THREAD

**Issue by abdugaliyev** [Amitpatil215/whatsapp_share#15]
deprecation alerts when build apk, whatsapp_share use deprecation api, and share doesnt work on android 13

**Comment by abdugaliyev** [comment]
Whatsapp Business is installed: true
E/flutter ( 4317): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(No Activity found to handle Intent { act=android.intent.action.SEND typ=text/plain flg=0x10000001 pkg=com.whatsapp clip={text/plain {T(313)}} (has extras) }, null, null, null)
E/flutter ( 4317): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter ( 4317): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter ( 4317): <asynchronous suspension>
E/flutter ( 4317): #2      WhatsappShare.share (package:whatsapp_share/whatsapp_share.dart:45:27)
E/flutter ( 4317): <asynchronous suspension>
E/flutter ( 4317): #3      _SendApartsDescState.build.<anonymous closure>.<anonymous closure> (package:chat_master_mobile_app/screens/inquiries/components/send_aparts_desc_form.dart:56:25)
E/flutter ( 4317): <asynchronous suspension>
E/flutter ( 4317):

**Comment by abdugaliyev** [comment]
<activity android:name="ShareActivity" android:exported="false">
            
            <intent-filter>
                <action android:name="android.intent.action.SEND"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <data android:mimeType="text/plain"/>
            </intent-filter>
            
            <intent-filter>
                <action android:name="android.intent.action.SEND"/>
                <action android:name="android.intent.action.SEND_MULTIPLE"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <data android:mimeType="application/vnd.google.panorama360+jpg"/>
                <data android:mimeType="image/*"/>
                <data android:mimeType="video/*"/>
            </intent-filter>
        </activity>
        
need add this to android manifest android/app/main/AndroidManifest.xml because android add new security rules to the 13 version.

**Comment by bayramaliunuvar** [comment]
The problem persists. When pressing the whatsapp send button on Android 13, it gives the following error.

`Exception has occurred.
PlatformException (PlatformException(No Activity found to handle Intent { act=android.intent.action.SEND typ=application/pdf flg=0x10000001 pkg=com.whatsapp clip={application/pdf {T(19)}} (has extras) }, null, null, null))`
